service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource:
        Ref: SNSTopic
  stage: dev
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SNS_ARN:
      Ref: SNSTopic
resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
        ReceiveMessageWaitTimeSeconds: 20
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: yakov.grischenko@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    SNSSubscriptionAdmin:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: coding@mail.ru
        Protocol: email
        FilterPolicy:
          priority:
            - high
        TopicArn:
          Ref: SNSTopic
  Outputs:
    SQSQueueUrl:
      Value:
        Ref: SQSQueue
    SQSQueueArn:
      Value:
        Fn::GetAtt: [SQSQueue, Arn]
functions:
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
  postProduct:
    handler: handler.postProduct
    events:
      - http:
          method: post
          path: products
          cors:
            origin: "*"
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors:
            origin: "*"
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          method: get
          path: products/{productId}
          cors:
            origin: "*"
